### DISCUSSION TITLE
可以增加在项目作为websocket客户端的情况下，同时连接多个服务端的功能吗

### DISCUSSION THREAD

**Discussion by zhu-weixin** [MisakaTAT/Shiro#265] [Ideas]

**Comment by zhu-weixin** [comment]
###  这个是我写的的连接多个websocket服务器的配置
```java
@Data
@Configuration
@ConfigurationProperties(prefix = "shiro.ws.client")
public class PluralBotClientConfig implements WebSocketConfigurer {
    /**
     * 是否启用多个正向 Websocket 连接
     */
    private Boolean enable = false;
    /**
     * 正向 Websocket 连接列表
     */
    private List<WebSocketClientProperties> clientProperties;

    @Autowired
    private ScheduledTask scheduledTask;
    @Autowired
    private WebSocketProperties wsProp;
    @Autowired
    private WebSocketClientHandler webSocketClientHandler;

    @Override
    public void registerWebSocketHandlers(WebSocketHandlerRegistry registry) {
        if (Boolean.TRUE.equals(enable)) {
            createWebsocketClients();
        }
    }

    private void createWebsocketClients() {
        for (WebSocketClientProperties clientProperty : clientProperties) {
            if (clientProperty.getEnable()) {
                StandardWebSocketClient client = new StandardWebSocketClient();
                WebSocketHttpHeaders headers = new WebSocketHttpHeaders();
                if (!Objects.equals(wsProp.getAccessToken(), "")) headers.add("Authorization", wsProp.getAccessToken());
                WebSocketConnectionManager manager = new WebSocketConnectionManager(client, webSocketClientHandler, clientProperty.getUrl());
                manager.setHeaders(headers);
                manager.setAutoStartup(true);
                scheduledTask.executor().scheduleAtFixedRate(() -> {
                    if (!manager.isConnected()) {
                        manager.startInternal();
                    }
                }, 0, clientProperty.getReconnectInterval(), TimeUnit.SECONDS);
            }
        }
    }
}

```
yml配置
```
shiro:
  ws:
    client:
      enable: true
      clientProperties:
        - enable: true
          url: "ws://*.*.*.*:8888"
          reconnectInterval: 5
        - enable: true
          url: "ws://*.*.*.*:8887"
          reconnectInterval: 5
```

### **但是连接间的相互通信和连接使用的插件管理还没有头绪**
目前只是大概的想法，但是可行性还未知：

> 连接使用的插件管理通过注解控制

> 连接间的相互通信通过线程池管理，设置公共缓存区域，方便共享数据和通信
